package com.example.algorithms;

import java.util.Random;
import com.example.constants.PathConstants;

/**
 *
 * The Java Class that takes in @see MazeGenerationAlgorithm and 
 * @see PathFindingAlgorithm as a composition and links it together
 * for generating and visualing maze algorithm and visualing the 
 * given Path Finding algorithm on hte maze generated by the maze
 * algorithm. As both needs each other to visualize a path.
 *
 * @author Shanand Shrestha
 *
**/
public class PathVisualizationAlgorithm extends Algorithm {
    private MazeGenerationAlgorithm mazeGenerationAlgorithm;
    private PathFindingAlgorithm pathFindingAlgorithm;
    private int[][] grid;
    private int startRow;
    private int startCol;
    private int endRow;
    private int endCol;
    
    public PathVisualizationAlgorithm(MazeGenerationAlgorithm mazeGenerationAlgorithm,
            PathFindingAlgorithm pathFindingAlgorithm) {
        this.mazeGenerationAlgorithm = mazeGenerationAlgorithm;
        this.pathFindingAlgorithm = pathFindingAlgorithm;
        ANIMATION_SPEED = 50;
    }

    @Override
    protected void generateRandomArray() {
        grid = new int[20][30];
        setRandomStartAndEndPoint(); 
    }
    
    private void setRandomStartAndEndPoint() {
        Random random = new Random();
        int nRow = grid.length;
        int nCol = grid[0].length;
        startRow = random.nextInt(nRow-2) + 1;
        startCol = random.nextInt(nCol/5) + 1;
        endRow = random.nextInt(nRow-2) + 1;
        endCol = random.nextInt(nCol/5 - 1) + nCol - (nCol/6) - 1;
        grid[startRow][startCol] = PathConstants.START_POINT;
        grid[endRow][endCol] = PathConstants.END_POINT;
    }

    @Override
    protected void processAlgorithm() throws InterruptedException {
        mazeGenerationAlgorithm.grid = grid;
        mazeGenerationAlgorithm.generateRandomArray();
        mazeGenerationAlgorithm.processAlgorithm();
        pathFindingAlgorithm.grid = mazeGenerationAlgorithm.grid;
        setStartAndEndPointCoordinates();
        pathFindingAlgorithm.generateRandomArray();
        pathFindingAlgorithm.processAlgorithm();
    }
    
    private void setStartAndEndPointCoordinates() {
        pathFindingAlgorithm.startRow = startRow;
        pathFindingAlgorithm.startCol = startCol;
        pathFindingAlgorithm.endRow = endRow;
        pathFindingAlgorithm.endCol = endCol;
    }

}
