package com.example.algorithms;

/**
 *
 * The Java Class that takes in @see MazeGenerationAlgorithm and 
 * @see PathFindingAlgorithm as a composition and links it together
 * for generating and visualing maze algorithm and visualing the 
 * given Path Finding algorithm on hte maze generated by the maze
 * algorithm. As both needs each other to visualize a path.
 *
 * @author Shanand Shrestha
 *
**/
public class PathVisualizationAlgorithm extends Algorithm {
    private MazeGenerationAlgorithm mazeGenerationAlgorithm;
    private PathFindingAlgorithm pathFindingAlgorithm;
    
    public PathVisualizationAlgorithm(MazeGenerationAlgorithm mazeGenerationAlgorithm,
            PathFindingAlgorithm pathFindingAlgorithm) {
        this.mazeGenerationAlgorithm = mazeGenerationAlgorithm;
        this.pathFindingAlgorithm = pathFindingAlgorithm;
    }

    @Override
    protected void generateRandomArray() {
        
    }

    @Override
    protected void processAlgorithm() throws InterruptedException {
        mazeGenerationAlgorithm.visualize();
        pathFindingAlgorithm.visualize();
    }


}
